# Generated by Django 4.2 on 2023-05-20 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('foto', models.ImageField(null=True, upload_to='foto')),
            ],
        ),
        migrations.CreateModel(
            name='formulario_contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('mensaje', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('foto', models.ImageField(null=True, upload_to='foto')),
                ('email', models.EmailField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miMakween.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('idTrabajo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
                ('publicar', models.BooleanField(default=False)),
                ('comentario', models.TextField(default='--')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miMakween.categoria')),
                ('mecanico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miMakween.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='galeria_imagenes',
            fields=[
                ('idFoto', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='foto')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miMakween.trabajos')),
            ],
        ),
    ]
