# Generated by Django 4.2 on 2023-05-20 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miMakween', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='categoria',
        ),
    ]
