# Generated by Django 4.2 on 2023-05-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miMakween', '0002_remove_usuario_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajos',
            name='foto',
            field=models.ImageField(default='foto/CarExample.png', null=True, upload_to='galeria_imagenes'),
        ),
    ]
