# Generated by Django 4.2 on 2023-05-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miMakween', '0003_trabajos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria_imagenes',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Galeria'),
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='foto',
            field=models.ImageField(default='foto/CarExample.png', null=True, upload_to='foto'),
        ),
    ]
