# Generated by Django 4.2 on 2023-05-20 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miMakween', '0004_alter_galeria_imagenes_imagen_alter_trabajos_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='galeria',
            fields=[
                ('idFoto', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(null=True, upload_to='Galeria')),
            ],
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='mecanico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='galeria_imagenes',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='galeria',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miMakween.trabajos'),
        ),
    ]
