# Generated by Django 4.1.5 on 2023-05-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miMakween', '0009_remove_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='foto/adult-school.png', null=True, upload_to='foto'),
        ),
    ]
