# Generated by Django 4.2 on 2023-06-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miMakween', '0010_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
    ]
